### ISSUE TITLE
how to send contact request?

### ISSUE THREAD

**Issue by vinnitu** [ShyykoSerhiy/skyweb#15]
I saw new feature you added yesterday, but I don't understand how to send contact request to other contact?

**Comment by ShyykoSerhiy** [comment]
Sending contact requests and searching for contacts is on the way aren't currently implemented (it's scheduled for 0.0.3). 
For now it's only possible to accept or decline contact requests that was sent to you.

**Comment by vinnitu** [comment]
Hm, I send request from linux skype and from web.skype.com but I don't see any accept action :-\ Does it work correctly?

**Comment by ShyykoSerhiy** [comment]
It has it's limitation. The polling for auth requests is executed every 120 seconds (otherwise skype sends "too much requests" error and refuses to give auth requests at all), so there may be 120 seconds lag.

**Comment by ShyykoSerhiy** [comment]
It probably will be fixed in next release.

**Comment by ShyykoSerhiy** [comment]
And make sure that you've cloned the repo and not installed via npm. Version with support for auth requests isn't on npm yet.

**Comment by vinnitu** [comment]
I used git clone

**Comment by ShyykoSerhiy** [comment]
Can you please check your logs for smth like "Something went wrong!Failed to accept friend"

**Comment by vinnitu** [comment]
nothing except 

```
Skyweb is initialized now
Here is some info about you:{
  "username": "...",
  "namespace": null,
  "displayname": "...",
  "firstname": "...",
  "lastname": null
}
Your contacts : [
  {
    "authorized": true,
```

**Comment by frakseno** [comment]
I was actually trying to start a demo and did get:

Something went wrong!Failed to get registrationToken.

**Comment by frakseno** [comment]
running it on linux instead of OSX, i am not getting :+1: 
/home/ashneyder/skyweb/dist/login.js:14
        var functions = [new Promise(this.sendLoginRequest.bind(this, skypeAcc
                             ^
ReferenceError: Promise is not defined
    at Login.doLogin (/home/ashneyder/skyweb/dist/login.js:14:30)
    at Skyweb.login (/home/ashneyder/skyweb/dist/skyweb.js:19:42)
    at Object.<anonymous> (/home/ashneyder/skyweb/dist/demo/demo.js:8:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by ShyykoSerhiy** [comment]
@ashneyder I've added e6-promise polyfill, It should work now on older node, so "ReferenceError: Promise is not defined" shouldn't occur. 
As for "Something went wrong!Failed to get registrationToken.":
I've added more details to error message. Please try again and provide error message.

**Comment by gamelaster** [comment]
Sending of contact request is not implemented yet i think, and its actually dont possible, couse skype for web have bug, when user accepts u, you still see him as "not accepted".
